[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
remappings = [
  "@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
gas_reports = ["ExposureBudgetIsm"]
fs_permissions = [{ access = "read-write", path = "../data" }]
